#                                                 üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•
#                                                üíªScavenger Hunt Configüíª
#                                                   üî•Coded By Mike3132üî•
#                                                üíªScavenger Hunt Configüíª
#                                                 üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•üñ•

Version: 'Version 1.0'
ConfigVersion: '1.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#‚úç‚úç‚úç‚úç‚úçPermissions‚úç‚úç‚úç‚úç‚úç
#ADMIN PERMISSIONS
#ScavengerHunt.Command.Hunt -> Permission to use admin only commands
#ScavengerHunt.Command.Admin -> Permission to enter and exit the admin mode for placing a break heads
#ScavengerHunt.Command.Admin.Reset -> Permission to reset a target players head count
#ScavengerHunt.Command.Admin.Placed -> Permission to list all heads in the current world
#ScavengerHunt.Command.Admin.ListOther -> Permission to view the amount of heads target player has found

#PLAYER PERMISSIONS
#ScavengerHunt.Command.Heads -> Permission to use player commands
#ScavengerHunt.Command.Heads.Found -> Permission to see how many heads they have found
#ScavengerHunt.Command.Heads.Near -> Permission to see if there is any heads placed nearby the player


#‚úç‚úç‚úç‚úç‚úçPermissions‚úç‚úç‚úç‚úç‚úç

#####You can Modify the following how you wish#####

#‚û≥‚û≥‚û≥‚û≥‚û≥ Head Item ‚û≥‚û≥‚û≥‚û≥‚û≥
#This is the head database id that the head will become, You can find the heads and their id's here > https://minecraft-heads.com
Hdb-Head-Id: "63573"

#This is the name of the head that will be displayed in the inventory
Head-Name-Inventory: "&6Spooky Ghost Head"

#This is the lore of the head that will be displayed in the inventory
Head-Lore-List:
  - '&eThis is a custom head'
  - ''
  - '&2Place this in the world to begin the hunt'

#‚û≥‚û≥‚û≥‚û≥‚û≥ Compass Item ‚û≥‚û≥‚û≥‚û≥‚û≥
#Should we enable the custom compass item
Compass-Item-Enabled: true

#Should the compass have uses?
#If this is enabled when a player clicks a compass it will remove 1 custom compass from their inventory stack
Infinite-Compass: true

#This is the distance to the nearest head a player needs to be for the compass to work
Compass-Distance: 5

#This is the name of the compass item
Compass-Name: "&5Head Finder"

#This is the lore of the compass (You need to manually set the amount of blocks the compass works with in the lore)
Compass-Lore-List:
  - '&eRight click this compass to find nearby heads'
  - ''
  - '&2Only works if you are within 5 blocks of a head'

#‚û≥‚û≥‚û≥‚û≥‚û≥ Armorstand ‚û≥‚û≥‚û≥‚û≥‚û≥
#Should we spawn an armorstand when the player claims a head
Armorstand-Animation: true

#Should we play a sound when the player claims a head
Armorstand-Sound: true

#This is the message that shows above the armorstand when the animation plays and is enabled
Armorstand-Message: "&6Spooky"


#‚û≥‚û≥‚û≥‚û≥‚û≥ Player Click Options ‚û≥‚û≥‚û≥‚û≥‚û≥
#Should the player receive a message when they click on a head. This message can be configured in the messages.yml file
Player-Messages-Enabled: true


#See messages.yml for all configurable plugin messages
#‚ôè If you have any questions please join my discord, open a support ticket and @Mike3132
#‚ôè https://discord.gg/ePQGvQuzG3
#‚ôè Thanks for downloading and have a wonderful day

#‚ôõ‚ôõ‚ôõ‚ôõ‚ôõ END OF CONFIG ‚ôõ‚ôõ‚ôõ‚ôõ‚ôõ
#This is the default config file.